### ISSUE TITLE
Investigate test runner / suite

### ISSUE THREAD

**Issue by KerimCETINBAS** [edunota/edunota-backend#1]
It is better start with testing before we implement any logic

investigate a testing library
- unit testing
- code coverage
- e2e
- integration

lets discuss our testing approach in comments/discord

**Comment by caglarcercinli** [comment]
- before commit all tests must pass (unit testing).
- which library? 
- code coverage 
- e2e testing: cypress
- integration testing: postman

**Comment by caglarcercinli** [comment]
testify for unit testing
